---
proxy_command: "ssh {{ ansible_user }}@{{ hostvars[groups.bastion[0]].ansible_host }} exec nc -w300 %h %p"
ssh_proxy_command: "ProxyCommand {{ proxy_command }}"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyCommand='{{ proxy_command }}'"
