---
# ansible-playbook ansible/app-rolling-upgrade.yml -e app_version=v2 
#
# Extra args:
#    -e app_version= 
#         v1 or v2 or v3 (existing version of app)

- import_playbook: lb-host.yml

- name: Upgrade application in place
  become: true
  hosts: app
  # Serial attribute
  serial: 1
  tags:
    - app
  vars:
    database_host: "{{ groups.db[0] }}"

  tasks:

    # ADD disable application at lb
    - name: Disable application at load balancer
      haproxy:
        backend: catapp-backend
        host: "{{ web_server }}"
        state: disabled
      delegate_to: "{{ item }}"
      loop: "{{ groups.loadbalancer }}"

    - import_tasks: tasks/setup-app.yml

    # ADD flush handlers
    - meta: flush_handlers

    # ADD wait for 5000
    - name: Make sure gunicorn is accepting connections
      wait_for:
        port: 5000
        timeout: 60

    # ADD enable application at lb
    - name: Re-enable application at load balancer
      haproxy:
        backend: catapp-backend
        host: "{{ web_server }}"
        state: enabled
      delegate_to: "{{ item }}"
      loop: "{{ groups.loadbalancer }}"


  handlers:
    - name: restart gunicorn
      systemd:
        name: gunicorn
        state: restarted

