---

# ansible-playbook app-blue-green-upgrade.yml 
#
#   Extra args:
#   -e app_version=[v1,v2,v3]
#    
#    Note: v1,v2,v3 are available versions of sample app
#
#   -e live=[blue,green]
#     blue is default
#      
#- import_playbook: sort-inventory-hosts.yml
- import_playbook: lb-host.yml

# ADD set active group




- import_playbook: blue-green-start-switch.yml

- name: Update app in inactive half of cluster
  become: true
  # ADD set to update


  any_errors_fatal: true
  vars:
    database_host: "{{ groups.db[0] }}"
  tasks:
    - import_tasks: tasks/setup-app.yml

    # ADD flush handlers and check port




    # ADD check version display



  handlers:
    - name: restart gunicorn
      systemd:
        name: gunicorn
        state: restarted


# ADD enable traffic to inactive




# ADD disable traffic to active side
