---
# ansible-playbook ansible/app-rolling-upgrade.yml -e app_version=v2 
#
# Extra args:
#    -e app_version= 
#         v1 or v2 or v3 (existing version of app)

- import_playbook: lb-host.yml

- name: Upgrade application in place
  become: true
  hosts: app
  # Serial attribute

  tags:
    - app
  vars:
    database_host: "{{ groups.db[0] }}"

  tasks:

    # ADD disable application at lb





    - import_tasks: tasks/setup-app.yml

    # ADD flush handlers



    # ADD wait for 5000



    # ADD enable application at lb




  handlers:
    - name: restart gunicorn
      systemd:
        name: gunicorn
        state: restarted

