- name: Set ansible_host for private hosts
  hosts: private_net
  gather_facts: false
  serial: 1
  vars:
    ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyCommand='ssh {{ ansible_user }}@{{ hostvars[groups.bastion[0]].ansible_host }} exec nc -w300 {{ openstack.private_v4 }} %p'" 
  tasks:
    - name: Assign groups from host set
      add_host:
        name: "{{ inventory_hostname }}"
        ansible_host: "{{ openstack.private_v4 }}"
        ansible_ssh_common_args: "{{ ssh_common_args }}"
