- name: Setup local environment
  hosts: localhost
  roles:
    - role: cloud-config
      openstack_config_directory: "{{ playbook_dir }}/.."
      cloud_name: catalystcloud
      os_username: "{{ ansible_env.OS_USERNAME }}"
      os_project_name: "{{ ansible_env.OS_PROJECT_NAME }}"
      os_project_id: "{{ ansible_env.OS_PROJECT_ID }}"
      os_password: "{{ ansible_env.OS_PASSWORD }}"
      os_region_name: "{{ ansible_env.OS_REGION_NAME }}"
