- name: Setup local environment
  hosts: localhost
  tasks:
    - name: Create local cloud file
      copy:
        content: "{{ cloud_config }}"
        dest: "{{ playbook_dir }}/../clouds.yaml"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644




