
- name: Sort hosts and pick out bastion
  hosts: all:!localhost
  gather_facts: false
  serial: 1
  tasks:

    - name: Assign host info for bastion
      add_host:
        name: "{{ openstack.metadata.inventory_hostname }}"
        ansible_host: "{{ openstack.public_v4  }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes"
        groups:
          - mybastion
      when:
        - openstack is defined
        - openstack.metadata.inventory_hostname is defined
        - openstack.metadata.inventory_hostname is search(prefix)
        - "'bastion' in group_names"

- name: Sort dynamic hosts into rollingupgrade group
  hosts: all:!localhost
  gather_facts: false
  serial: 1
  tasks:
    - name: Assign groups from host set
      add_host:
        name: "{{ openstack.metadata.inventory_hostname }}"
        ansible_host: "{{ openstack.private_v4 }}"
        groups: "{{ openstack.metadata.groups }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyCommand='ssh {{ hostvars[openstack.metadata.inventory_hostname].ansible_user }}@{{ hostvars[groups.mybastion[0]].ansible_host }} exec nc -w300 %h %p'"
      when:
        - openstack is defined
        - openstack.metadata.inventory_hostname is defined
        - openstack.metadata.inventory_hostname is search(prefix)
        - "'behindbastion' in group_names"


    - name: Assign host info for bastion
      add_host:
        name: "{{ openstack.metadata.inventory_hostname }}"
        groups:
          - rollingupdate
      when:
        - openstack is defined
        - openstack.metadata.inventory_hostname is search(prefix)
        - openstack.metadata.inventory_hostname is defined
