
- name: Process dynamic inventory for bastion hosts
  hosts: bastion
  gather_facts: false
  serial: 1
  vars:
    ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes" 
  tasks:

    - name: Assign host info for bastion
      add_host:
        name: "{{ openstack.metadata.inventory_hostname }}"
        ansible_host: "{{ openstack.public_v4  }}"
        ansible_ssh_common_args: "{{ ssh_common_args }}"
        groups:
          - deployed_bastion
      when:
        - openstack is defined
        - openstack.metadata.inventory_hostname is defined
        - openstack.metadata.inventory_hostname is search(prefix)

- name: Process dynamic inventory for private hosts
  hosts: private_net
  gather_facts: false
  serial: 1
  vars:
    ssh_common_args: "-o StrictHostKeyChecking=no -o ForwardAgent=yes -o ProxyCommand='ssh {{ hostvars[openstack.metadata.inventory_hostname].ansible_user }}@{{ hostvars[groups.deployed_bastion[0]].ansible_host }} exec nc -w300 %h %p'" 
  tasks:
    - name: Assign groups from host set
      add_host:
        name: "{{ openstack.metadata.inventory_hostname }}"
        ansible_host: "{{ openstack.private_v4 }}"
        groups: "{{ openstack.metadata.groups }}"
        ansible_ssh_common_args: "{{ ssh_common_args }}"
        groups:
          - deployed_private
      when:
        - openstack is defined
        - openstack.metadata.inventory_hostname is defined
        - openstack.metadata.inventory_hostname is search(prefix)
